import { useMemo } from "react";

export const Component = () => {
    const autoGeneratedIds = useMemo<string[]>(() => {
        return Array.from({ length: 100 }, () =>
            Math.random().toString(36).substr(2, 9)
        );
    }, []);
}